version: 2

sources:
  - name: public
    tables:
      - name: ahs_factures
      - name: csm_factures

models:

  - name: dim_date
    description: "Date dimension populated automatically from raw factures/...."
    columns:
      - name: full_date
        description: "Primary key"
        tests:
          - unique
    config:
      schema: transformed

  - name: fact_factures
    description: "Fact table for factures"
    columns:
      - name: src_id
        description: "Primary key of the fact table"
        tests:
          - not_null
      - name: date_facture
        description: "Foreign key to dim_date.full_date"
        tests:
          - relationships:
              to: ref('dim_date')
              field: full_date
    config:
      schema: transformed
          
