version: 2

# RAW Tables

sources:
  - name: __raw_
    tables:
    
    # Factures
      - name: ahs_factures
      - name: csm_factures
      - name: occ_factures
      - name: cz_factures
      - name: sahara_factures

    # Communes
      - name: ahs_communes
      - name: csm_communes
      - name: occ_communes
      - name: cz_communes
      - name: sahara_communes

    # Exercises
      - name: ahs_exercices
      - name: csm_exercices
      - name: occ_exercices
      - name: cz_exercices
      - name: sahara_exercices

    # Mise en demeure
      - name: ahs_miseen_demeure
      - name: csm_miseen_demeure
      - name: occ_miseen_demeure
      - name: cz_miseen_demeure
      - name: sahara_miseen_demeure

    # P eau
      - name: ahs_p_eau
      - name: csm_p_eau
      - name: occ_p_eau
      - name: cz_p_eau
      - name: sahara_p_eau

    # Payements
      - name: ahs_payements
      - name: csm_payements
      - name: occ_payements
      - name: cz_payements
      - name: sahara_payements

    # Prelevement volume
      - name: ahs_prelevement_volume
      - name: csm_prelevement_volume
      - name: occ_prelevement_volume
      - name: cz_prelevement_volume
      - name: sahara_prelevement_volume

    # Recours
      - name: ahs_recours
      - name: csm_recours
      - name: occ_recours
      - name: cz_recours
      - name: sahara_recours

    # Wilaya
      - name: ahs_wilaya
      - name: csm_wilaya
      - name: occ_wilaya
      - name: cz_wilaya
      - name: sahara_wilaya

    # Unités
      - name: ahs_unites
      - name: csm_unites
      - name: occ_unites
      - name: cz_unites
      - name: sahara_unites

# Models for dwh tables defined with constraints

models:

  ############
  # DIMENSIONS
  ############

  # communes
  - name: dim_communes
    description: "dim ..."
    columns:
      - name: src_id
        description: "Primary key of the fact table"
        tests:
          - not_null
    config:
      schema: dwh


  # TABLE usagers
  - name: dim_usagers
    description: "... dimension"
    columns:

      - name: usagers_id
        description: "Primary key"
        tests:
          - unique
          - not_null

    config:
      schema: dwh 


  # TABLE exercice
  - name: dim_exercices
    description: "... dimension"
    columns:

      - name: exercice_id
        description: "Primary key"
        tests:
          - unique
          - not_null

    config:
      schema: dwh 


  # TABLE recours
  - name: dim_recours
    description: "... dimension"
    columns:

      - name: recours_id
        description: "Primary key"
        tests:
          - unique
          - not_null

    config:
      schema: dwh 

  
  # TABLE p_eau
  - name: dim_p_eau
    description: "... dimension"
    columns:

      - name: p_eau_id
        description: "Primary key"
        tests:
          - unique
          - not_null

    config:
      schema: dwh 








  ############
  # FACTS
  ############
  
  # FACTURES
  - name: fact_factures
    description: "Fact table for factures"
    columns:

      - name: src_id
        description: "Primary key of the fact table"
        tests:
          - not_null

      - name: date_facture
        description: "Foreign key to dim_date.full_date"
        tests:
          - relationships:
              to: ref('dim_date')
              field: full_date

    config:
      schema: dwh
          
  # ENCAISSEMENT
  - name: fact_encaissement
    description: "Fact table for encaissement"
    columns:

      - name: date_encaissement
        description: "Foreign key to dim_date.full_date"
        tests:
          - relationships:
              to: ref('dim_date')
              field: full_date

    config:
      schema: dwh

  # PRELEVEMENT
  - name: fact_prelevement
    description: "Fact table for Prelevement"

    columns:

      - name: prelevement_id
        description: "Primary key"
        tests:
          - unique
          - not_null

    config:
      schema: dwh

  # MDEMEURE
  - name: fact_mise_en_demeure
    description: "Fact table for Mise en demeure"
    columns:

      - name: src_id
        description: "Primary key of the fact table"
        tests:
          - not_null

      - name: date_med
        description: "Foreign key to dim_date.full_date"
        tests:
          - relationships:
              to: ref('dim_date')
              field: full_date

    config:
      schema: dwh

