version: 2

sources:
  - name: public
    tables:
      - name: ahs_factures
      - name: csm_factures
      - name: occ_factures
      - name: cz_factures
      - name: sahara_factures
      - name: ahs_communes
      - name: csm_communes
      - name: occ_communes
      - name: cz_communes
      - name: sahara_communes
      - name: ahs_type_etat_compteur
      - name: csm_type_etat_compteur
      - name: occ_type_etat_compteur
      - name: cz_type_etat_compteur
      - name: sahara_type_etat_compteur

models:

  - name: dim_date
    description: "Date dimension populated automatically from raw factures/...."
    columns:
      - name: full_date
        description: "Primary key"
        tests:
          - unique
    config:
      schema: transformed

  - name: fact_factures
    description: "Fact table for factures"
    columns:
      - name: src_id
        description: "Primary key of the fact table"
        tests:
          - not_null
      - name: date_facture
        description: "Foreign key to dim_date.full_date"
        tests:
          - relationships:
              to: ref('dim_date')
              field: full_date
    config:
      schema: transformed

  
  - name: dim_communes
    description: "dim ..."
    columns:
      - name: src_id
        description: "Primary key of the fact table"
        tests:
          - not_null
    config:
      schema: transformed

  - name: dim_type_etat_compteur
    description: "dim ..."
    columns:
      - name: src_id
        description: "Primary key of the fact table"
        tests:
          - not_null
    config:
      schema: transformed    
          
