version: 2

sources:
  - name: public
    tables:
      - name: ahs_factures
      - name: csm_factures

models:
  - name: merge_tables
    description: "Data from source AHS"
    config:
      schema: consolidated_schema
      alias: fact_factures

