version: 2

sources:
  - name: public
    tables:
    
    # Factures
      - name: ahs_factures
      - name: csm_factures
      - name: occ_factures
      - name: cz_factures
      - name: sahara_factures

    # Communes
      - name: ahs_communes
      - name: csm_communes
      - name: occ_communes
      - name: cz_communes
      - name: sahara_communes

    # Exercises
      - name: ahs_exercices
      - name: csm_exercices
      - name: occ_exercices
      - name: cz_exercices
      - name: sahara_exercices

    # Mise en demeure
      - name: ahs_miseen_demeure
      - name: csm_miseen_demeure
      - name: occ_miseen_demeure
      - name: cz_miseen_demeure
      - name: sahara_miseen_demeure

    # P eau
      - name: ahs_p_eau
      - name: csm_p_eau
      - name: occ_p_eau
      - name: cz_p_eau
      - name: sahara_p_eau

    # Payements
      - name: ahs_payements
      - name: csm_payements
      - name: occ_payements
      - name: cz_payements
      - name: sahara_payements

    # Prelevement volume
      - name: ahs_prelevement_volume
      - name: csm_prelevement_volume
      - name: occ_prelevement_volume
      - name: cz_prelevement_volume
      - name: sahara_prelevement_volume

    # Recours
      - name: ahs_recours
      - name: csm_recours
      - name: occ_recours
      - name: cz_recours
      - name: sahara_recours

    # Type Activité
      - name: ahs_type_activite
      - name: csm_type_activite
      - name: occ_type_activite
      - name: cz_type_activite
      - name: sahara_type_activite

    # Type Décision Recours
      - name: ahs_type_decision_recour
      - name: csm_type_decision_recour
      - name: occ_type_decision_recour
      - name: cz_type_decision_recour
      - name: sahara_type_decision_recour

    # Type Estimation
      - name: ahs_type_estimation
      - name: csm_type_estimation
      - name: occ_type_estimation
      - name: cz_type_estimation
      - name: sahara_type_estimation

    # Type État Compteur
      - name: ahs_type_etat_compteur
      - name: csm_type_etat_compteur
      - name: occ_type_etat_compteur
      - name: cz_type_etat_compteur
      - name: sahara_type_etat_compteur

    # Type Nature P Eau
      - name: ahs_type_nature_p_eau
      - name: csm_type_nature_p_eau
      - name: occ_type_nature_p_eau
      - name: cz_type_nature_p_eau
      - name: sahara_type_nature_p_eau

    # Type Paiement
      - name: ahs_type_paiement
      - name: csm_type_paiement
      - name: occ_type_paiement
      - name: cz_type_paiement
      - name: sahara_type_paiement

    # Type Statut
      - name: ahs_type_statut
      - name: csm_type_statut
      - name: occ_type_statut
      - name: cz_type_statut
      - name: sahara_type_statut

    # Type Unité
      - name: ahs_type_unite
      - name: csm_type_unite
      - name: occ_type_unite
      - name: cz_type_unite
      - name: sahara_type_unite

    # Wilaya
      - name: ahs_wilaya
      - name: csm_wilaya
      - name: occ_wilaya
      - name: cz_wilaya
      - name: sahara_wilaya

    # Unités
      - name: ahs_unites
      - name: csm_unites
      - name: occ_unites
      - name: cz_unites
      - name: sahara_unites

    # Type État Unité
      - name: ahs_type_etat_unite
      - name: csm_type_etat_unite
      - name: occ_type_etat_unite
      - name: cz_type_etat_unite
      - name: sahara_type_etat_unite

models:

# TABLE date
  - name: dim_date
    description: "Date dimension populated automatically from raw factures/...."
    columns:
      - name: full_date
        description: "Primary key"
        tests:
          - unique
    config:
      schema: transformed

# TABLE factures
  - name: fact_factures
    description: "Fact table for factures"
    columns:
      - name: src_id
        description: "Primary key of the fact table"
        tests:
          - not_null
      - name: date_facture
        description: "Foreign key to dim_date.full_date"
        tests:
          - relationships:
              to: ref('dim_date')
              field: full_date
    config:
      schema: transformed

  # TABLE communes
  - name: dim_communes
    description: "dim ..."
    columns:
      - name: src_id
        description: "Primary key of the fact table"
        tests:
          - not_null
    config:
      schema: transformed
 

  # TABLE type_etat_compteur
  - name: dim_type_etat_compteur
    description: "... dimension"
    columns:

      - name: etat_compteur_id
        description: "Primary key"
        tests:
          - unique
          - not_null

    config:
      schema: transformed     

    # TABLE encaissement
  - name: fact_encaissement
    description: "... dimension"
    columns:

      - name: encaissement_id
        description: "Primary key"
        tests:
          - unique
          - not_null

    config:
      schema: transformed  

      # TABLE prelevement
  - name: fact_prelevement
    description: "... dimension"
    columns:

      - name: prelevement_id
        description: "Primary key"
        tests:
          - unique
          - not_null

    config:
      schema: transformed  
          

                # TABLE usagers
  - name: dim_usagers
    description: "... dimension"
    columns:

      - name: usagers_id
        description: "Primary key"
        tests:
          - unique
          - not_null

    config:
      schema: transformed 


                  # TABLE exercice
  - name: dim_exercices
    description: "... dimension"
    columns:

      - name: exercice_id
        description: "Primary key"
        tests:
          - unique
          - not_null

    config:
      schema: transformed 


                      # TABLE recours
  - name: dim_recours
    description: "... dimension"
    columns:

      - name: recours_id
        description: "Primary key"
        tests:
          - unique
          - not_null

    config:
      schema: transformed 

                  # TABLE p_eau
  - name: dim_p_eau
    description: "... dimension"
    columns:

      - name: p_eau_id
        description: "Primary key"
        tests:
          - unique
          - not_null

    config:
      schema: transformed 


               # TABLE type_paiement
  - name: dim_type_paiement
    description: "... dimension"
    columns:

      - name: type_paie_id
        description: "Primary key"
        tests:
          - unique
          - not_null

    config:
      schema: transformed 
                  # TABLE type_nature_p_eau
  - name: dim_type_nature_p_eau
    description: "... dimension"
    columns:

      - name: nature_p_eau_id
        description: "Primary key"
        tests:
          - unique
          - not_null

    config:
      schema: transformed 

             # TABLE type_usagers
  - name: dim_type_usagers
    description: "... dimension"
    columns:

      - name: type_usagers_id
        description: "Primary key"
        tests:
          - unique
          - not_null

    config:
      schema: transformed 


             # TABLE mode_estimation
  - name: dim_mode_estimation
    description: "... dimension"
    columns:

      - name: mode_estimation_id
        description: "Primary key"
        tests:
          - unique
          - not_null

    config:
      schema: transformed 

      # TABLE type_decision_recours
  - name: dim_type_decision_recour
    description: "... dimension"
    columns:

      - name: decision_id
        description: "Primary key"
        tests:
          - unique
          - not_null

    config:
      schema: transformed 


      # TABLE etat_usagers
  - name: dim_etat_usagers
    description: "... dimension"
    columns:

      - name: etat_usagers_id
        description: "Primary key"
        tests:
          - unique
          - not_null


# TABLE statut_usagers
  - name: dim_statut_usagers
    description: "... dimension"
    columns:

      - name: statut_usager_id
        description: "Primary key"
        tests:
          - unique
          - not_null


    config:
      schema: transformed 

# TABLE type_activité
  - name: dim_type_activité
    description: "... dimension"
    columns:

      - name: type_activite_id
        description: "Primary key"
        tests:
          - unique
          - not_null


    config:
      schema: transformed 

  # # TABLE
  # - name: dim_...
  #   description: "... dimension"
  #   columns:

  #     - name: ..._id
  #       description: "Primary key"
  #       tests:
  #         - unique
  #         - not_null

  #   config:
  #     schema: transformed